package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u251/737/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, March 11, 2020 11:21:55 PM PDT
*/


/** Server callback API, passed to Activator in active method.
    */
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
