package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u251/737/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, March 11, 2020 11:21:55 PM PDT
*/

public interface ServerManager extends ServerManagerOperations, com.sun.corba.se.spi.activation.Activator, com.sun.corba.se.spi.activation.Locator
{
} // interface ServerManager
