package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u251/737/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, March 11, 2020 11:21:56 PM PDT
*/

public interface RMICustomMaxStreamFormat
{

  /**
       * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
       * service context which contains a single byte specifying
       * the client's maximum RMI-IIOP stream format version.
       *
       * See Java to IDL ptc/02-01-12 1.4.12.
       */
  public static final int value = (int)(17L);
}
